version: "3.8"
services:
  redis:
    container_name: "redis"
    image: redis:6.2
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7001:6379"
    volumes:
      - $PWD/Redis/redis.conf:/usr/local/etc/redis/redis.conf